version: 2.1


jobs:
  test:  
    docker:
      - image: painless/tox 
        environment: 
          MONGO_URI: "mongodb://localhost:27017/"
      - image: mongo:4.4.8
    steps:
      - checkout
      - restore_cache:
        keys:
          - tox-{{ checksum 'src/requirements_dev.txt' }}-{{ checksum 'src/requirements.txt' }}
      - run:
          name: Run tests
          command: tox -p auto .
      - run:
          name: Install codecov
          command: pip install codecov
      - run:
          name: Send coverage
          command: codecov
      - save_cache:
          key: tox-{{ checksum 'src/requirements_dev.txt' }}-{{ checksum 'src/requirements.txt' }}
          paths:
            - ~/project/.tox


workflows:
  test-and-build: 
    jobs:
      - test
