version: 2.1


jobs:
  test:  
    docker:
      - image: painless/tox 
        environment: 
          MONGO_URI: "mongodb://localhost:27017/"
      - image: mongo:4.4.8
    steps:
      - checkout
      - run:
          name: create test results folder
          command: mkdir test_results
      - run:
          name: Run tests
          command: tox -p auto .
      - run:
          name: Install codecov
          command: pip install codecov
      - run:
          name: Send coverage
          command: codecov

workflows:
  test-and-build: 
    jobs:
      - test
