version: 2.1

workflows:
  sample: 
    jobs:
      - test

jobs:
  test:  
    docker:
      - image: painless/tox 
    steps:
      - checkout
      - run:
          name: Run tests
          command: tox -p auto .
