version: 2.1


jobs:
  test:  
    docker:
      - image: painless/tox 
        environment: 
          MONGO_URI: "mongodb://localhost:27017/"
      - image: mongo:4.4.8
    steps:
      - checkout
      - run:
          name: Run flake8
          command: tox -e flake8 -p auto .
      - run:
          name: Run tests
          command: tox -e py{35,36,37,38} -p auto .
      - run:
          name: Send coverage
          command: tox -e coverage -p auto .

workflows:
  test-and-build: 
    jobs:
      - test
