version: 2.1

executors:
  builder:
    docker:
      - image: circleci/python
  tester:
    docker:
      - image: painless/tox 
        environment: 
          MONGO_URI: "mongodb://localhost:27017/"
      - image: mongo:4.4.8

jobs:
  test:  
    executor: tester
    steps:
      - checkout
      - restore_cache:
          keys:
            - tox-{{ checksum "src/requirements_dev.txt" }}-{{ checksum "src/requirements.txt" }}
      - run:
          name: Run tests
          command: tox -p auto .
      - run:
          name: Install codecov
          command: pip install codecov
      - run:
          name: Send coverage
          command: codecov
      - save_cache:
          key: tox-{{ checksum "src/requirements_dev.txt" }}-{{ checksum "src/requirements.txt" }}
          paths:
            - ~/project/.tox

  build-compose:
    executor: builder
    steps:
      - setup_remote_docker:
          version: 20.10.6
      - checkout
      - run:
          name: Run compose
          command: |
            set -x
            ls -lRa
            docker-compose build
            docker-compose up -d -p 8080:8080
            curl http://localhost:8080/api/v1/restaurant


workflows:
  test-and-build: 
    jobs:
      - test
      - build-compose
