replicaCount: 1

image:
  repository: blopezp007/mongo
  pullPolicy: Always
  tag: "1.0.0"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 27017

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  - name: MONGO_INITDB_ROOT_USERNAME
    value: mongoadmin
  - name: MONGO_INITDB_DATABASE
    value: restaurant
  - name: MONGO_USERNAME
    value: mongo

env_secrets: 
  - env: MONGO_INITDB_ROOT_PASSWORD
    secret_name: mongo
    secret_key: MONGO_INITDB_ROOT_PASSWORD
  - env: MONGO_PASSWORD
    secret_name: mongo
    secret_key: MONGO_PASSWORD


nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  MONGO_INITDB_ROOT_PASSWORD: ""
  MONGO_PASSWORD: ""
