replicaCount: 1

image:
  repository: blopezp007/app
  pullPolicy: Always
  tag: "1.0.0"

nameOverride: ""
fullnameOverride: "restaurant"

serviceAccount:
  create: false
  annotations: {}
  name: "default"

podAnnotations: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /api/v1/restaurant
          pathType: Exact
          backend:
            service:
              name: restaurant
              port:
                number: 8080
        - path: /api/v1/restaurant
          pathType: Prefix
          backend:
            service:
              name: restaurant
              port:
                number: 8080
env: []

env_secrets: 
  - env: MONGO_URI
    secret_name: restaurant
    secret_key: MONGO_URI

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

secrets:
  mongo_uri: ""
