apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongo.fullname" . }}
  labels:
    {{- include "mongo.labels" . | nindent 4 }}
type: Opaque
data:
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.secrets.MONGO_INITDB_ROOT_PASSWORD | b64enc | quote }}
  MONGO_PASSWORD: {{ .Values.secrets.MONGO_PASSWORD | b64enc | quote }}
